version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
       - ./app/:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:11.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Set_db_9876
      - POSTGRES_DB=set_manager_db

volumes:
  postgres_data: