# Generated by Django 4.1 on 2022-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor", name="Cheque_Number", field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="donor", name="Phone_Number", field=models.BigIntegerField(),
        ),
    ]
