# Generated by Django 4.1 on 2022-08-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_donor_cheque_number_alter_donor_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="Amount",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name="donor", name="From_To", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="donor",
            name="On_Account_Of",
            field=models.CharField(max_length=200),
        ),
    ]
