# Generated by Django 4.1 on 2022-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_donor_amount_alter_donor_from_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='Token',
            field=models.CharField(default='none', max_length=7),
            preserve_default=False,
        ),
    ]
